### PR TITLE
Show Debug line & Editor's Breakpoint

### PR DESCRIPTION
**Pull request by x2nie**
Hi !
I am adding an hightlight of current running line (in xml editor, and code visualization too).
I also integrate the debug breakpoint (red circle) into xml editor
image
image

My work is not perfect, but I think it add a little bit more understandability, and it adds more fun, I think.

### CODE REVIEW

**Comment by Yuu6883** [comment]
Nice work, I'll take a look later today

**Comment by Yuu6883** [comment]
It would be nice if the breakpoint from visualization and XML editor is synced (the breakpoint from XML editor isn't working for me)

**Comment by x2nie** [comment]
You're wrong, Yu. 
It is actually working, but if put a breakpoint on a rule under `sequence`, it might be there for a while during the rule loop.
Can you put a debug breakpoint on the last child of a `markov` ?

**Comment by x2nie** [comment]
these commits are included in #7

**Pull request closed without merging**
